# Generated by Django 2.2 on 2019-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'personmodel',
            },
        ),
    ]
